// IATA airport code -> the city the globe should label it with. The flights
// table stores dep_city/arr_city per row, but seventeen years of imported
// history arrived with codes only, so this fills them in — and gives new
// rows a name without a lookup service.
//
// The city, not the airport: LGW, LTN and LHR are all "London", which is
// what makes the globe group them into one pin instead of three overlapping
// ones. Mirrors the code set in airportCoords.js and airportTz.js.
export const AIRPORT_CITY = {
  ADL: 'Adelaide',
  AKL: 'Auckland',
  AMS: 'Amsterdam',
  ANU: 'Antigua',
  ARN: 'Stockholm',
  ASP: 'Alice Springs',
  ATL: 'Atlanta',
  AUH: 'Abu Dhabi',
  AVV: 'Melbourne',
  BCN: 'Barcelona',
  BER: 'Berlin',
  BKI: 'Kota Kinabalu',
  BKK: 'Bangkok',
  BNA: 'Nashville',
  BNE: 'Brisbane',
  BOS: 'Boston',
  BUD: 'Budapest',
  BVC: 'Boa Vista',
  CAN: 'Guangzhou',
  CDG: 'Paris',
  CFU: 'Corfu',
  CHC: 'Christchurch',
  CMB: 'Colombo',
  CNS: 'Cairns',
  CNX: 'Chiang Mai',
  CPH: 'Copenhagen',
  CPT: 'Cape Town',
  CVG: 'Cincinnati',
  DCA: 'Washington',
  DEL: 'Delhi',
  DFW: 'Dallas',
  DME: 'Moscow',
  DMK: 'Bangkok',
  DOH: 'Doha',
  DPS: 'Bali',
  DTW: 'Detroit',
  DUB: 'Dublin',
  DXB: 'Dubai',
  EDI: 'Edinburgh',
  EWR: 'New York',
  FCO: 'Rome',
  FRA: 'Frankfurt',
  GLA: 'Glasgow',
  HAN: 'Hanoi',
  HBA: 'Hobart',
  HEL: 'Helsinki',
  HIA: "Huai'an",
  HKG: 'Hong Kong',
  HND: 'Tokyo',
  HNL: 'Honolulu',
  IAD: 'Washington',
  ICN: 'Seoul',
  JFK: 'New York',
  KBV: 'Krabi',
  KTM: 'Kathmandu',
  KUL: 'Kuala Lumpur',
  LAS: 'Las Vegas',
  LAX: 'Los Angeles',
  LCY: 'London',
  LGA: 'New York',
  LGW: 'London',
  LHR: 'London',
  LIM: 'Lima',
  LIS: 'Lisbon',
  LTN: 'London',
  MAD: 'Madrid',
  MAN: 'Manchester',
  MEL: 'Melbourne',
  MIA: 'Miami',
  MSY: 'New Orleans',
  MXP: 'Milan',
  NCE: 'Nice',
  NRT: 'Tokyo',
  OGG: 'Maui',
  OOL: 'Gold Coast',
  OPO: 'Porto',
  ORD: 'Chicago',
  OSL: 'Oslo',
  PEK: 'Beijing',
  PER: 'Perth',
  PHL: 'Philadelphia',
  PMI: 'Palma',
  SCL: 'Santiago',
  SEA: 'Seattle',
  SFO: 'San Francisco',
  SHA: 'Shanghai',
  SIN: 'Singapore',
  SLC: 'Salt Lake City',
  SOF: 'Sofia',
  SYD: 'Sydney',
  TXL: 'Berlin',
  VIE: 'Vienna',
  WLG: 'Wellington',
  YQB: 'Quebec City',
  YVR: 'Vancouver',
  YYZ: 'Toronto',
}
