// IATA airport code -> IANA timezone. Used to render each flight's times
// in *local* time at the relevant airport (dep_time local to dep_airport,
// arr_time local to arr_airport) — the DB stores everything as UTC.
export const AIRPORT_TZ = {
  ADL: 'Australia/Adelaide',
  AKL: 'Pacific/Auckland',
  ANU: 'America/Antigua',
  ARN: 'Europe/Stockholm',
  ASP: 'Australia/Darwin',
  AUH: 'Asia/Dubai',
  AVV: 'Australia/Melbourne',
  BCN: 'Europe/Madrid',
  BKI: 'Asia/Kuala_Lumpur',
  BNA: 'America/Chicago',
  BOS: 'America/New_York',
  BUD: 'Europe/Budapest',
  BVC: 'Atlantic/Cape_Verde',
  CDG: 'Europe/Paris',
  CIA: 'Europe/Rome',
  CFU: 'Europe/Athens',
  CHC: 'Pacific/Auckland',
  CNS: 'Australia/Brisbane',
  CNX: 'Asia/Bangkok',
  CPH: 'Europe/Copenhagen',
  CPT: 'Africa/Johannesburg',
  CVG: 'America/New_York',
  DCA: 'America/New_York',
  DEL: 'Asia/Kolkata',
  DFW: 'America/Chicago',
  DME: 'Europe/Moscow',
  DOH: 'Asia/Qatar',
  DPS: 'Asia/Makassar',
  DTW: 'America/New_York',
  DUB: 'Europe/Dublin',
  DXB: 'Asia/Dubai',
  FRA: 'Europe/Berlin',
  HAN: 'Asia/Ho_Chi_Minh',
  HBA: 'Australia/Hobart',
  HIA: 'Asia/Shanghai',
  HNL: 'Pacific/Honolulu',
  IAD: 'America/New_York',
  KTM: 'Asia/Kathmandu',
  LCY: 'Europe/London',
  LGA: 'America/New_York',
  LGW: 'Europe/London',
  LIM: 'America/Lima',
  LTN: 'Europe/London',
  MAD: 'Europe/Madrid',
  MXP: 'Europe/Rome',
  NCE: 'Europe/Paris',
  NRT: 'Asia/Tokyo',
  OGG: 'Pacific/Honolulu',
  OOL: 'Australia/Brisbane',
  ORD: 'America/Chicago',
  OSL: 'Europe/Oslo',
  PER: 'Australia/Perth',
  PHL: 'America/New_York',
  PMI: 'Europe/Madrid',
  SCL: 'America/Santiago',
  SEA: 'America/Los_Angeles',
  SFO: 'America/Los_Angeles',
  SLC: 'America/Denver',
  SOF: 'Europe/Sofia',
  TXL: 'Europe/Berlin',
  VIE: 'Europe/Vienna',
  YQB: 'America/Toronto',
  YVR: 'America/Vancouver',
  YYZ: 'America/Toronto',
  AMS: 'Europe/Amsterdam',
  ATL: 'America/New_York',
  BER: 'Europe/Berlin',
  BKK: 'Asia/Bangkok',
  BNE: 'Australia/Brisbane',
  CAN: 'Asia/Shanghai',
  CMB: 'Asia/Colombo',
  DMK: 'Asia/Bangkok',
  EDI: 'Europe/London',
  EWR: 'America/New_York',
  FCO: 'Europe/Rome',
  GLA: 'Europe/London',
  HEL: 'Europe/Helsinki',
  HKG: 'Asia/Hong_Kong',
  HND: 'Asia/Tokyo',
  ICN: 'Asia/Seoul',
  JFK: 'America/New_York',
  KBV: 'Asia/Bangkok',
  KUL: 'Asia/Kuala_Lumpur',
  LAS: 'America/Los_Angeles',
  LAX: 'America/Los_Angeles',
  LHR: 'Europe/London',
  LIS: 'Europe/Lisbon',
  MAN: 'Europe/London',
  MEL: 'Australia/Melbourne',
  MIA: 'America/New_York',
  MSY: 'America/Chicago',
  OPO: 'Europe/Lisbon',
  PEK: 'Asia/Shanghai',
  SHA: 'Asia/Shanghai',
  SIN: 'Asia/Singapore',
  SYD: 'Australia/Sydney',
  WLG: 'Pacific/Auckland',
}

export function localTime(iso, airportCode) {
  if (!iso) return ''
  const tz = AIRPORT_TZ[airportCode]
  if (!tz) return iso.slice(11, 16) // unknown airport: fall back to the raw stored value
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: tz,
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  }).format(new Date(iso))
}

export function localDate(iso, airportCode) {
  if (!iso) return ''
  const tz = AIRPORT_TZ[airportCode]
  const opts = { day: 'numeric', month: 'short', year: 'numeric' }
  if (tz) opts.timeZone = tz
  return new Intl.DateTimeFormat('en-GB', opts).format(new Date(iso))
}
