-- Journal entries for sri-lanka-voyage + bangkok, reconstructed from the
-- merged Google Timeline export (timelinecomplete.json.gz, 5 Mar–6 Jun 2026).
-- Times converted from the export's +11:00 display offset to destination local.

update public.trips set subtitle='Berlin → London → Colombo → Melbourne' where slug='sri-lanka-voyage';

delete from public.journal_entries where trip_id=(select id from trips where slug='sri-lanka-voyage');
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-03-21', 1, 'Berlin', 'Berlin → London → the night flight south', 'The Voyage opens in Berlin — flew in from Heathrow the evening before (BA990). A 5 km run through the city at 06:20, a couple of hours to breathe, then BA975 back to London at 11:50. The evening turn: UL504 out of Heathrow at 20:40, the SriLankan A330 pointed at Colombo overnight. The gap year''s longest single travel corridor begins.', '🏃', '{"gps","run","travel"}', 52.52, 13.405 from public.trips where slug='sri-lanka-voyage';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-03-22', 2, 'Colombo', 'Colombo — one evening in Sri Lanka', 'Wheels down at Bandaranaike just after 13:00 local, a 30 km car ride into Colombo. The GPS shows a proper evening despite the layover-length stay: three stops across the city between 15:00 and 21:00 — around two and a half hours at the first, dinner-length pauses at the others — before the 21:15 run back to the airport. Not a beach holiday; a deliberate waypoint. Sri Lanka: touched, logged, to be returned to.', '🌴', '{"gps","travel"}', 6.9271, 79.8612 from public.trips where slug='sri-lanka-voyage';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-03-23', 3, 'Melbourne', 'CMB → MEL — the arrival', 'UL604 lifted out of Colombo at 00:25 and put down in Melbourne at 15:53 — the flight that ends the northern-hemisphere chapter. A car from the airport, a few first-evening stops, and by nightfall the GPS settles into what becomes the Melbourne home pattern. The next morning it''s already a 16 km run around the new city. The mini gap year now has a base.', '🇦🇺', '{"gps","travel","milestone"}', -37.8136, 144.9631 from public.trips where slug='sri-lanka-voyage';

delete from public.journal_entries where trip_id=(select id from trips where slug='bangkok');
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-03', 1, 'Bangkok', 'Melbourne → KUL → Bangkok', 'MH146 out of Melbourne mid-morning, a tight 28-minute connection at KUL — the GPS barely registers the terminal before MH774 pushes back — and into Suvarnabhumi by 17:30. The 39 km run into the city lands at the hotel around 19:15. First Thai evening kept short; the trip starts properly at dawn.', '✈️', '{"gps","travel"}', 13.74, 100.55 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-04', 2, 'Bangkok', 'The dawn 14k and the first full day', 'Run of the trip: 14 km through Bangkok starting 05:23, done before the heat arrived. Then the day unfolds in the GPS like a proper first day — an early two-hour stop, a 3 km walk through the old town late morning, a 24 km drive across the city, a string of afternoon visits, and back by evening. The rhythm that carried the whole trip: run at dawn, city by day, early night.', '🏃', '{"gps","run"}', 13.73, 100.524 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-05', 3, 'Bangkok', 'Old town on foot + the Chao Phraya ferry', 'A 7 km walk starting 05:00 — the temples-and-lanes morning, done before the tour groups. Midday stops around the old town, then the day''s best move: the 13:13 Chao Phraya express ferry, 7 km down the river, an hour at the far end before the evening. The river is Bangkok''s proper avenue and the GPS finally shows it used as one.', '⛴️', '{"gps","walk","river"}', 13.7437, 100.493 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-06', 4, 'Ao Nang', 'Bangkok → Krabi — down to the beach', 'A 5 km morning walk and a bus hop, then out to Suvarnabhumi for FD4400 — the Thai AirAsia hop south to Krabi at 13:47. A 25 km transfer to Ao Nang, and by 16:45 the GPS is on the beach strip: two and a half hours along the front as the sun went down, then an early night. The one proper beach chapter of the whole gap year.', '🏝️', '{"gps","travel","krabi"}', 8.035, 98.82 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-07', 5, 'Krabi', 'Ao Nang morning → back to Bangkok', 'A slow Ao Nang morning — three unhurried stops along the beachfront between 06:30 and 09:00 — then the 23 km ride to Krabi Town and an hour and a bit around it. FD3211 lifts off at 11:30 for Don Mueang, and by 14:00 the GPS is back in the Bangkok evening. Twenty hours of beach, executed precisely.', '🌅', '{"gps","travel","krabi"}', 8.062, 98.91 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-08', 6, 'Bangkok', 'The 13k and the deep city day', 'Dawn again: 13 km through the city from 04:22 — the earliest start of the trip. Then the longest single stop of the week (a two-hour-plus morning anchor), a 3 km midday walk, and an afternoon threaded through four or five shorter visits across town. The GPS reads like someone who has stopped being a visitor and started running errands in Bangkok.', '🏃', '{"gps","run"}', 13.731, 100.53 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-09', 7, 'Bangkok', 'Last Bangkok day → the night flight out', 'A last short run at dawn (6 km in two legs), one long late-morning stop, a subway hop, and a final unhurried afternoon of wandering and small visits. At 14:42 the 38 km run out to Suvarnabhumi, three hours in the terminal, and MH781 away at 18:53 — the overnight positioning to KUL, with a bed at the airport hotel on the other end.', '🛫', '{"gps","run","travel"}', 13.745, 100.535 from public.trips where slug='bangkok';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-04-10', 8, 'Melbourne', 'KUL → MEL — home', 'A KUL airport-hotel morning (the GPS shows the Sama-Sama shuffle: sleep, breakfast, terminal), then MH129 the long way south — 6,390 km — touching down in Melbourne at 19:59. A 26 km ride home to South Melbourne and the trip closes exactly a week after it opened. Bangkok done: two dawn runs, one ferry, one beach, zero wasted days.', '🏠', '{"gps","travel"}', -37.851, 144.984 from public.trips where slug='bangkok';

