-- NZ + Korea/HK journals from the full on-device Timeline export
-- (Timeline.json, 5 Mar–8 Jul 2026, 3,646 semantic segments). Times
-- converted from the export's +10:00 display offset to destination local.

delete from public.journal_entries where trip_id=(select id from trips where slug='new-zealand');
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-15', 1, 'Wellington', 'Status Run One — MEL → SYD → WLG', 'Run One begins. A Melbourne morning of errands, then QF448 at 13:30 and a three-and-a-half-hour Sydney layover before QF163 pushed off for Wellington. Wheels down near midnight NZ time, a quick ride into town, checked in just after midnight. The whole day exists purely to move a dot across the Tasman — the tier points don''t earn themselves.', '🛫', '{"gps","travel","status-run"}', -41.29, 174.78 from public.trips where slug='new-zealand';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-16', 2, 'Wellington', 'The Wellington run', 'The day the trip was for, in a way: the 17.9 km Wellington run at 10:22 — the harbourfront, Oriental Bay and back, 55 PRs and achievements pinged on Strava by the end. A slow breakfast beforehand, a couple of stops after, and by mid-afternoon the GPS settles in for the evening. One full Wellington day, used properly.', '🏃', '{"gps","run","strava"}', -41.286, 174.776 from public.trips where slug='new-zealand';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-17', 3, 'Wellington', 'WLG → BNE → MEL — the long way home', 'Checkout, four hours at Wellington airport, then the status-run signature move: QF282 to Brisbane rather than anything direct. Two and a half hours in the BNE precinct — the airport dinner that becomes a ritual — then QF1259 down to Melbourne, home just after midnight. Run One complete: four sectors, 6,865 km, Wellington for one perfect run.', '✈️', '{"gps","travel","status-run"}', -41.3272, 174.8074 from public.trips where slug='new-zealand';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-22', 8, 'Wellington', 'Status Run Two — same again, please', 'A week at home in Melbourne between runs (including a 17.9 km long run on the 19th to keep the legs honest), then the identical playbook: QF448 to Sydney — this time with a five-hour layover — and QF163 across to Wellington, arriving after midnight again. The GPS trace of this day is almost a carbon copy of the 15th, which is exactly the point.', '🔁', '{"gps","travel","status-run"}', -41.29, 174.78 from public.trips where slug='new-zealand';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-23', 9, 'Wellington', 'Wellington, the slower lap', 'No run logged this time — a different Wellington. A two-hour morning stop from 10:30, a stroll through town, then a five-hour afternoon anchored in one spot (the GPS suggests a long working lunch that simply refused to end). Evening in from 19:30. The second visit has the ease of a place already figured out.', '☕', '{"gps","wellington"}', -41.289, 174.777 from public.trips where slug='new-zealand';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-24', 10, 'Wellington', 'Run Two home — tier secured', 'A 4 km morning walk along the waterfront, the local bus to the airport, and the same two-hop home: QF282 to Brisbane at 15:40, the ritual airport dinner (two stops, nearly three hours), QF1259 to Melbourne, in the door just before 1am. Two identical weeks, eight sectors, ~13,700 km — the NZ Tier Run, executed twice and done.', '🏁', '{"gps","travel","status-run","milestone"}', -41.3272, 174.8074 from public.trips where slug='new-zealand';

delete from public.journal_entries where trip_id=(select id from trips where slug='south-korea');
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-30', 1, 'Hong Kong', 'Melbourne → Sydney → Hong Kong', 'A pre-dawn start (the GPS clocks movement from 4:30am), out to Melbourne airport by 7:00 and a long lounge morning before the Sydney hop. Then CX100 — the 777 to Hong Kong, 7,394 km — touching down at 21:55 local. First night spent right at the airport precinct: the sensible move with a Seoul flight the next evening.', '🛫', '{"gps","travel"}', 22.308, 113.9185 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-01', 2, 'Hong Kong', 'Hong Kong in a day — run, MTR, town, fly', 'A 3.1 km shakeout run at 05:57 around Tung Chung under the airport''s flight path, then the day used properly: MTR into Kowloon at 09:00, a 4 km wander, a long lunch stop on the island side, back on the MTR by 15:00. CX426 — the A321neo — lifted off for Seoul at 19:45. Hong Kong: 22 hours, one run, one proper look.', '🏃', '{"gps","run","travel"}', 22.29, 114.17 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-02', 3, 'Seoul', 'Seoul, day one', 'Landed Incheon after midnight, the 56 km run into the city, hotel by 1:30am. The first day unfolds gently in the GPS: a late start, buses and walks across the centre, a two-hour early-afternoon stop, more zigzagging, and an early night. Jet-lag day, spent on foot the way first days should be.', '🌆', '{"gps","arrival"}', 37.556, 126.972 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-03', 4, 'Seoul', 'The Han River 16k + Myeongdong', 'The ''Seoul 🇰🇷'' run: 16.0 km along the Han River from Yongsan at 06:21, relative effort 195 — the hardest run of the whole gap year on Strava''s math. Brunch near Itaewon, a midday of stops around Yongsan, then across to Myeongdong and Jongno on foot for the afternoon. Evening lands in Gangnam/Apgujeong and stays there — new neighbourhood, second act of the trip.', '🏃', '{"gps","run","strava"}', 37.53, 126.99 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-04', 5, 'Seoul', 'The big one — 17.8 km at dawn', 'Longest run of the Korea leg: 17.8 km from Apgujeong at 05:25, the Han River paths again before the heat. A long brunch afterwards (2 hours 19 — earned), one errand, and then the GPS goes quiet from mid-afternoon: a genuine rest evening. Three runs in four days; the legs got a night off.', '🏃', '{"gps","run"}', 37.52, 127.028 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-05', 6, 'Seoul', '16.4k, then the subway grand tour', 'Run three of three: 16.4 km at 05:58, completing 50+ km in Seoul across three mornings. Then a day the metro map would be proud of — Apgujeong to Itaewon by car, subway hops through Myeongdong, City Hall and back to Yongsan, before an evening settled around Itaewon. The Seoul chapter''s last full day.', '🏃', '{"gps","run","subway"}', 37.532, 126.995 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-06', 7, 'Seoul', 'Last Seoul day → Incheon', 'A farewell circuit by subway: Myeongdong in the morning, a Gangnam detour, a two-hour Itaewon lunch. At 16:50 the airport bus — 60 km out to Incheon — then the lounge, and CX427 away late for Hong Kong. The GPS shows the classic end-of-trip shape: one last loop of the favourites, then the long ride out.', '🛍️', '{"gps","travel"}', 37.534, 126.994 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-07', 8, 'Hong Kong', 'The HKG marathon layover → Sydney', 'Arrived Hong Kong in the small hours and simply lived at the airport — the GPS logs one continuous 20-hour presence at HKG, overnight through to the morning 777. CX139 to Sydney, 7,394 km, landing 20:10. Overnight at the airport hotel with one more trick planned for sunrise.', '✈️', '{"gps","travel"}', 22.313, 113.915 from public.trips where slug='south-korea';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-07-08', 9, 'Sydney', 'The airport-to-harbour run, then home', 'The gap year''s sign-off: at 05:56, a 10.7 km run from the Sydney airport hotel up to the harbour and Circular Quay — sunrise over the bridge on legs that had done Seoul three days running — then a car straight back to the terminal. VA826 to Melbourne at 09:58, home by midday. Trip six of six complete. The mini gap year ends the way it was lived: with a dawn run and a boarding pass.', '🌅', '{"gps","run","milestone"}', -33.885, 151.218 from public.trips where slug='south-korea';

