update public.trips set photos_url='https://photos.app.goo.gl/jzsvoEfUq4X3tezm6', subtitle='CΛNΛRD sourcing leg · MEL → HK → GZ → SH → BJ → Tokyo → SYD' where slug='china-japan';

delete from public.journal_entries where trip_id=(select id from trips where slug='china-japan');

insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-21', 1, 'Brisbane', 'Melbourne → Brisbane', 'Morning around Prahran and the Melbourne CBD, then the early-afternoon hop to Brisbane and the Airtrain into town. A few hours in the CBD before heading back out — spotted the airport gym on the way ("I saw Noah in there, getting some rowing practice in"). The CX156 redeye to Hong Kong pushed back at 00:05, seat 2A, Cathay Business on the A350.', '✈️', '{"travel","feeder"}', -27.4705, 153.026 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-22', 2, 'Guangzhou', '→ Hong Kong → Guangzhou', 'Landed Hong Kong 06:50, straight onto CX982 to Guangzhou. Into Tianhe by mid-morning, and this is where the trip''s real purpose began — the CΛNΛRD sourcing mission. First market contact warranted the text I sent: "Off to a market now. Deep breath." Overwhelming scale, WeChat Pay and Alipay to navigate, no English. Checked into the Sofitel Guangzhou Sunrich, Club Millésime.', '😮', '{"arrival","canard","markets"}', 23.1291, 113.2644 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-23', 3, 'Guangzhou', 'Guangzhou markets + a Shenzhen dash', 'Dawn 13.9 km along the Pearl River south bank (5:08/km). Then Zhongda Fabric Market and Baima Clothing Wholesale — swatches, MOQ questions, vendor WeChat contacts. The GPS caught an unplanned high-speed dash to Shenzhen and straight back: first class booked on the spot in the rain, a walk through Huaqiangbei, the world''s largest tech market. Late that night, early logo work: "Hours spent on that one. How the duck sits in a heart 🦆❤️".', '🏃', '{"run","canard","markets","shenzhen"}', 23.1155, 113.3235 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-24', 4, 'Shanghai', 'Guangzhou → Shanghai — the wasted day', 'Longest run of the trip first: 17.3 km on the Pearl River (5:18/km). Then Baiyun Airport''s business terminal — "it''s like T5 here" — until security confiscated the power bank at screening (a replacement sourced on JD before clearing the lane). A system-wide ATC hold turned the Shanghai board orange: one flight cancelled, ours held, sent back from the gate. Finally airborne ~14:36, China Eastern J, chicken burger or nothing, cabin "hotter than the sun." Wheels down 03:42. The Club Millésime frustration became Accor case 24066657.', '😤', '{"run","travel","delays"}', 31.2304, 121.4737 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-25', 5, 'Shanghai', 'Shanghai — the fashion awakening', '12.9 km along the Bund in bad weather (5:33/km). The Sofitel North Bund had mis-sold the club lounge — complaint filed, moved to the Swissôtel Grand Shanghai. The real shift was in the streets: young Shanghainese in Supreme, Carhartt and APC at a premium, while local designers did something far more interesting. "A duck with a beret isn''t the next big thing out there" — the self-awareness that would sharpen into a better question.', '🌧️', '{"run","fashion","canard"}', 31.234, 121.49 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-26', 6, 'Shanghai', 'Shanghai — who is this for?', 'A ~5.6 km walk through Jing''an. An early-morning photo at 05:52 that would later echo against the Comme des Garçons discovery in Tokyo — the same instinct, different execution. The reflection that landed: "The exxy Western brands the Asians wear... Maybe the market I''m going after is Asian. They have money, influence, and take risks."', '🤔', '{"fashion","reflection"}', 31.2304, 121.4737 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-27', 7, 'Shanghai', 'Shanghai — the pivot', 'Two walks around Xuhui and Huangpu. The Hong Kong leg dropped — "HKG just for tech and a bit more fashion — decided no." ANA business via Virgin locked in for Tokyo instead. Booked the Fairmont Beijing and the G4 train north. At 16:01 an ambiguous Trip.com "itinerary updated" email arrived — the fuse for the next morning.', '🗺️', '{"planning","pivot"}', 31.2304, 121.4737 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-28', 8, 'Beijing', 'Shanghai → Beijing — the missed train', 'Pre-dawn 8.9 km through Anfu Li (安福里) — Xuhui''s laneway of independent studios and concept stores, empty at 5am. "Amazing run by Anfu Li." Then the dash that went wrong: arrived Hongqiao for the 07:00, told wrong station, no Didi, a half-taxi turnaround when app and email contradicted. Back too late, rebooked onto the 08:00, into Beijing South at 12:37. Fairmont Beijing, Fairmont Gold. Complaint lodged for 200 CNY.', '😅', '{"run","travel","anfu-li"}', 39.9042, 116.4074 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-29', 9, 'Beijing', 'Beijing — hutongs over the Forbidden City', '16.1 km through Chaoyang (4:55/km), then a man doing slow sword tai chi in a park — one of those moments that stops you mid-stride. A boat segment on the Houhai lakes. "Been to this lovely street I found on social" — a hutong bar, one Dellboy drink, on-tenet — and an up-and-coming streetwear pocket. "Awful if I skipped the Forbidden City?" Skipped it. The hutong was better.', '🐉', '{"run","hutong","fashion"}', 39.9042, 116.4074 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-30', 10, 'Mutianyu', 'The Great Wall', 'Fastest run of the trip first — 16.0 km at 4:52/km, HR peaking at 185, the strongest physical day of the sixteen. Then a private driver out to Mutianyu: cable car up, towers 14 to 20 on foot, toboggan down (non-negotiable). A tea ceremony in the afternoon, and Subway for lunch ("Subway sounds interesting," said David Seeby). Last China night at the Hilton Beijing Capital Airport.', '🧱', '{"run","great-wall","highlight"}', 40.4319, 116.5704 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-05-31', 11, 'Tokyo', 'Beijing → Tokyo — the luggage tags', 'Final China run in the dark — 12.9 km around the airport (4:59/km). Then Virgin Australia to Haneda. The trip''s standout human moment: an ANA-curious flight attendant who spotted the luggage tags, sat down, and chatted properly. In Tokyo, standing in Comme des Garçons Aoyama triggered a long thread on Sacai and Chitose Abe''s hybrid construction — the 05:52 Shanghai image snapping into focus. ANA InterContinental Tokyo, high floor, staff rate.', '🛫', '{"run","fashion","canard","human"}', 35.6762, 139.7503 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-01', 12, 'Tokyo', 'Tokyo — the Hamarikyu run', 'The most beautiful run of the trip: 18.09 km through Hamarikyu Gardens at the mouth of the Sumida, then north through Minato (5:00/km). A café on the route produced the best photo of the whole sixteen days. A full working day off the ANA InterContinental''s 4pm checkout, then across to the Hilton Tokyo. "If fashion for me comes to nothing, if anything it has been a new lens into culture."', '🌅', '{"run","fashion","highlight"}', 35.66, 139.763 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-02', 13, 'Tokyo', 'Tokyo — the samples day', 'The day that made the trip. Morning 11.42 km through Shinjuku into Yoyogi. Then a typhoon warning that sent me to the embroidery shop a day early — "Shop said I had to come today as expecting the typhoon tomorrow." A printer who did everything on the day: embroidery, print, finished CΛNΛRD samples, handed over. Mercure Tokyo Hibiya, right by Ginza. That night, to David Seeby: "This is the best solo trip I have ever done."', '🧵', '{"run","canard","samples","highlight"}', 35.672, 139.76 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-03', 14, 'Tokyo', 'Typhoon Tokyo → Haneda', 'The typhoon day. Morning in Starbucks, an underground-connected gym, then Dover Street Market Ginza — right next to the Mercure all along, discovered only on the way out. The brand name resolved itself in the afternoon rain: kill the inverted-A ("reads as a maths symbol, fails embroidery"), go with the crossbar-less CΛNΛRD. Then Haneda Innovation City post-storm — craft beer, a dog café, planes in the windows. Villa Fontaine Grand Haneda for the last Japan night ("how the mighty have fallen — crap gym").', '🌀', '{"typhoon","fashion","canard","dsm"}', 35.5493, 139.7798 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-04', 15, 'Sydney', 'Tokyo → Sydney', 'Final Japan gym, checkout, then HND → SYD, about nine hours. GPS snaps back on at Circular Quay in the evening — a clean, sharp contrast with the previous night''s Kawasaki corridor. Sofitel Sydney Wentworth, right between The Rocks and Martin Place. That evening: "Fashion is not dead. It is such a fun space... No! It is this. Then a staple."', '✈️', '{"travel","fashion"}', -33.861, 151.211 from public.trips where slug='china-japan';
insert into public.journal_entries (trip_id, entry_date, day_number, city, title, note, mood, tags, lat, lon)
select id, '2026-06-05', 16, 'Sydney', 'Sydney — the harbour day', 'A dawn 7.85 km along Circular Quay and The Rocks — the trip''s tenth run, found only later in the GPS, unlogged at the time. Then nearly six hours around the harbour, a Martin Place meeting detour, a Phillip Street wander. Stayed on at the Sofitel Wentworth (the Hilton cancelled at no cost): "And this is so much better than the Hilton." The last day of the trip doing its best work.', '🌊', '{"run","sydney","harbour"}', -33.861, 151.211 from public.trips where slug='china-japan';

-- ── Hotel stays as map pins (Map tab layer) ──────────────────
delete from public.map_pins where trip_id=(select id from trips where slug='china-japan') and kind='hotel';
insert into public.map_pins (trip_id, kind, label, city, lat, lon, notes)
select id, 'hotel', v.label, v.city, v.lat, v.lon, v.notes from public.trips, (values
  ('Sofitel Guangzhou Sunrich',    'Guangzhou', 23.1310, 113.3300, 'Club Millésime · 22–24 May'),
  ('Swissôtel Grand Shanghai',     'Shanghai',  31.2360, 121.4560, '25–28 May · after the North Bund mis-sell'),
  ('Fairmont Beijing',             'Beijing',   39.9100, 116.4610, 'Fairmont Gold · 28–30 May'),
  ('Hilton Beijing Capital Airport','Beijing',  40.0600, 116.6000, 'Airline staff rate · 30–31 May'),
  ('ANA InterContinental Tokyo',   'Tokyo',     35.6690, 139.7400, 'High-floor king, staff rate · 31 May'),
  ('Hilton Tokyo',                 'Tokyo',     35.6910, 139.6920, 'Shinjuku · 1 Jun'),
  ('Mercure Tokyo Hibiya',         'Tokyo',     35.6730, 139.7590, 'Next to Dover Street Market Ginza · 2 Jun'),
  ('Villa Fontaine Grand Haneda',  'Tokyo',     35.5490, 139.7900, 'Inside HND · 3 Jun'),
  ('Sofitel Sydney Wentworth',     'Sydney',   -33.8660, 151.2100, 'The Rocks / Martin Place · 4–7 Jun')
) as v(label, city, lat, lon, notes)
where slug='china-japan';
